### ISSUE TITLE
07/31 병아리 디자인

### ISSUE THREAD

**Issue by aristo0922** [KPUCE2021SP/hummingbird#17]
07/28 ) 병아리 관련 자료 찾으면서 최대한 그려보기

07/29) 병아리 반응(꼬질이 버전 || 반짝이 버전 || 집 나가는 버전 완성) 

07/30) 프로토타입에 적용했을 때 사진이 깨지는 현상 발생... 수정 필요....

**Comment by hhhminme** [comment]
좋습니다 ㅎㅎ 그린 그림이랑 xml은 다음 회의때 함께 보여주시면 감사하겠습니다
